import { casinos, type Casino } from './casinos'

export type BonusFAQ = { q: string; a: string }

export type BonusContent = {
  intro: string
  faqs: BonusFAQ[]
  casinoFilter: (c: Casino) => boolean
}

export const BONUS_CONTENT: Record<string, BonusContent> = {
  'welcome-bonus': {
    intro:
      'The welcome bonus is the most aggressive marketing instrument in the crypto casino industry — operators routinely match 100% to 500% of a first deposit because the lifetime value of a converted player far exceeds the bonus cost. Match percentages cluster around 100% at established platforms like BitStarz (5 BTC across four deposits) and Cloudbet (100% up to 5 BTC), and climb to 300% or 325% at newer brands like Mirax Casino (325% up to $3,250 + 250 spins) and BC.Game. The higher the headline match, the harder the structure usually is to clear: wagering requirements sit at 35x to 50x of bonus or bonus-plus-deposit, and a maximum cashout cap of 5x to 10x of the bonus amount limits what you can actually withdraw if a bonus-funded session turns lucky. A first-deposit psychology drives the inflation: behavioural data shows new players overweight headline numbers and underweight playthrough math, which is why a 500% match with 50x wagering on bonus + deposit on slots-only is structurally less generous than a 100% match at 35x on bonus alone with broader game contribution. Before accepting any welcome offer, identify three numbers — the wagering multiplier, whether it applies to bonus or bonus plus deposit, and the maximum withdrawable amount. Crypto-specific notes: some casinos pay welcome bonuses in BTC equivalent, others in USDT, and a handful (BitStarz being the notable example) charge a 25% admin fee on bonus-related withdrawals — easy to miss in the small print.',
    faqs: [
      {
        q: 'How long do welcome bonuses take to credit?',
        a: 'At crypto casinos, welcome bonus funds typically credit within seconds of a qualifying deposit confirming on-chain — under 3 seconds for USDT on TRC-20, under 30 seconds for ETH, and 10-20 minutes for BTC depending on network conditions. Free spin portions of welcome packages usually credit immediately on deposit confirmation. If your bonus has not appeared within 30 minutes, contact live chat rather than re-depositing — duplicate deposits do not trigger duplicate bonuses.',
      },
      {
        q: 'Can I withdraw a welcome bonus without playing through it?',
        a: 'No. Every credible welcome bonus carries a wagering requirement that must be cleared before bonus funds and any associated winnings become withdrawable. Attempting to withdraw before clearing wagering forfeits the bonus and any winnings generated by it. The wagering applies to the bonus amount only at most operators (35x-40x) or to the bonus plus deposit combined at others (35x-50x) — always check which calculation applies before depositing.',
      },
      {
        q: 'Why do some welcome bonuses look much bigger than others?',
        a: 'Headline match percentages above 200% are usually compensated by harsher playthrough terms — typically 50x wagering on bonus-plus-deposit, restricted game contributions, lower max cashout caps and shorter expiration windows. A 100% match at 35x on bonus only with broad game contribution is structurally worth more than a 500% match at 50x on bonus-plus-deposit limited to slots. Compare expected value, not headline numbers.',
      },
      {
        q: 'Are welcome bonuses worth taking for table game players?',
        a: 'Usually not. Most welcome bonuses apply game-contribution rates of 5%-10% to blackjack, roulette and baccarat, which effectively multiplies the wagering requirement tenfold. A 35x wagering requirement becomes 350x in real terms for table game players. Some operators block table games from bonus wagering entirely. Players who primarily play blackjack or roulette should either decline welcome bonuses or seek operators with explicit table-game-friendly bonus terms.',
      },
      {
        q: 'Can I split my welcome bonus across multiple deposits?',
        a: 'This depends on the structure. Single-deposit welcome bonuses lock the offer to your first deposit only — anything you did not claim is gone. Multi-deposit welcome packages (BitStarz across four deposits, Mirax across four, 7Bit with reload track) explicitly support splitting the bonus, with separate match percentages and caps on each step. Multi-step structures are friendlier for players who want to test the platform before committing a large deposit.',
      },
    ],
    casinoFilter: () => true,
  },

  'no-deposit-bonus': {
    intro:
      'A no deposit bonus is the casino industry’s equivalent of a free sample — operators give away $10-$50 in bonus credit or 20 to 50 free spins to first-time registrants without requiring a deposit, treating the cost as a lead-generation expense rather than a marketing match. The mechanics split into two categories: automatic bonuses credited at signup (most common at newer crypto brands) and code-redeemed offers requiring an exclusive bonus code entered during registration or in the cashier. Both forms carry the most restrictive terms in the entire bonus landscape. Wagering requirements typically run 50x to 70x of the bonus amount — a $20 no deposit bonus at 60x demands $1,200 in turnover before any winnings can be withdrawn. Maximum cashout caps are similarly aggressive: $50 to $100 is the standard ceiling regardless of how much you actually win during wagering. Some operators add an additional clause that requires a single qualifying deposit before any bonus-derived winnings clear. Eligible games are usually restricted to a specific slot or a curated handful of titles, blocking the higher-RTP options where players might otherwise grind down the playthrough efficiently. KYC verification is mandatory before payout in almost all cases — operators have learnt the hard way that no-KYC plus no-deposit invites systematic bonus abuse. Genuine no deposit bonuses are rare at established crypto casinos in 2026; most have phased them out in favour of larger welcome packages that require an initial deposit and provide better unit economics.',
    faqs: [
      {
        q: 'Where do I find no deposit bonus codes?',
        a: 'Code-driven no deposit bonuses are usually distributed through affiliate sites, the casino’s own email list for re-engagement, or social media promotions. Sites that aggregate working codes update them frequently because individual codes expire or get rate-limited. The casino’s cashier section rarely lists no deposit codes — they are acquisition tools targeted at new registrants. Always verify the code is still valid before completing registration, as expired codes typically cannot be applied retroactively.',
      },
      {
        q: 'Why is the max cashout so low on no deposit bonuses?',
        a: 'The cap is structural risk management. A $20 free bonus at 60x wagering theoretically lets a lucky player turn nothing into a few thousand dollars, which would make the offer economically unsustainable. Caps of $50-$100 mean the operator’s worst-case payout is bounded. From the casino’s perspective the offer exists to convert registrations into first-time depositors, not to fund player profits — the cap aligns the structure with that goal.',
      },
      {
        q: 'Do I need to verify my identity to withdraw no deposit bonus winnings?',
        a: 'Yes, almost universally. No deposit promotions are the most-abused bonus type in the industry — operators have seen organised attempts to register hundreds of accounts to extract free bonus winnings — so KYC is mandatory before any cashout. Even at no-KYC casinos that do not otherwise require documents, the bonus terms usually carve out an exception for promotional play. Expect to provide ID, address verification and sometimes a selfie before withdrawal clears.',
      },
      {
        q: 'Can I claim no deposit bonuses at multiple casinos with the same details?',
        a: 'You can attempt to, but most operators run shared anti-fraud systems that flag duplicate registrations across affiliated platforms. Players flagged at one casino in a brand network often find their accounts blocked at others in the same network. Some operators also check IP, device fingerprint and payment instrument for duplicates. Genuine first-time players have nothing to worry about; serial bonus hunters typically get caught quickly.',
      },
      {
        q: 'Are no deposit bonuses ever genuinely worth claiming?',
        a: 'For most players the expected value is positive but small — a $20 bonus at 60x with a $100 cap has a realistic expected return in the single-dollar range after accounting for slot RTP. The bigger value is qualitative: it lets you test the casino’s interface, customer support and game library risk-free before committing a deposit. Treat them as platform trials rather than profit opportunities and they make sense.',
      },
    ],
    casinoFilter: () => true,
  },

  'reload-bonus': {
    intro:
      'Reload bonuses are the workhorse retention tool of the crypto casino industry — offered to existing players on second, third or weekly deposits, they sit between the headline-grabbing welcome offer and the negligible value of free spins promotions. Typical match rates run 25% to 75%, with the most common structure being a 50% reload up to a $200-$500 cap. Cadence varies widely: BC.Game and BitStarz run a continuous Monday Reload or weekly reload tied to a player’s account tier, while Cloudbet and 7Bit Casino structure reloads as part of multi-step welcome packages spanning the first four deposits. Wagering requirements on reloads are usually friendlier than the initial welcome match — 25x to 35x on bonus only is standard, against 35x to 50x for the welcome offer — which makes them genuinely worth taking for active players. The retention psychology is well documented in industry data: a 50% reload offer at a 30x playthrough has a marginal expected value high enough to justify the cost of marketing the reload, but the structure relies on what behavioural economists call sunk-cost reasoning — players who accept reloads typically deposit more frequently and at higher average values than those who decline them. The smart use case is treating reloads as a small efficiency boost on planned deposits rather than as a reason to deposit at all. If the bonus would not be worth it without the reload, the deposit probably is not worth it with one either. Always check whether the reload caps stack or override your current pending bonus balance.',
    faqs: [
      {
        q: 'How often can I claim a reload bonus?',
        a: 'Cadence varies by operator. BitStarz runs a Monday reload available once per week to accounts that have made at least one prior deposit. BC.Game offers daily reload tied to VIP tier with maximum claim limits per 24 hours. Cloudbet structures reloads within a multi-deposit welcome track rather than as recurring offers. Always check the specific terms — some "weekly" reloads run Sun-Sat, others 7-day rolling from your last claim.',
      },
      {
        q: 'Is the wagering on a reload bonus easier than the welcome bonus?',
        a: 'Usually yes. Welcome bonuses typically carry 35x-50x wagering because the operator is paying high acquisition cost. Reloads serve retention, where the player is already known to be active, so wagering drops to 25x-35x at most operators. Maximum cashout caps are also typically higher on reloads (10x-20x of bonus versus 5x-10x on welcome offers), making the effective expected value of a reload claim higher per dollar of bonus.',
      },
      {
        q: 'Can I claim a reload bonus without playing through previous bonus money?',
        a: 'At most operators yes — reloads stack with previously cleared bonus funds. However, you usually cannot have an active unwagered bonus running when you claim a new one. Some platforms automatically forfeit any pending bonus balance when you opt in to a fresh reload, which means partially-wagered welcome bonuses can disappear if you accept a reload before clearing them. Read carefully before clicking claim.',
      },
      {
        q: 'Do reload bonuses contribute to VIP tier progression?',
        a: 'Real-money wagering counts toward VIP points regardless of whether the funds came from a deposit or a reload bonus. Wagering performed with bonus money typically counts at a lower contribution rate (often 50%) toward VIP progression — operators want to prevent bonus-funded volume from inflating VIP tier benefits. The exact ratios are usually published in the VIP terms; if they are not, the answer is almost always less favourable than for cash wagering.',
      },
      {
        q: 'Is it worth taking a reload bonus if I plan to withdraw soon?',
        a: 'No. A reload bonus only delivers value if you complete the wagering requirement — abandoning it midway means forfeiting both the bonus amount and any winnings on top. If your deposit horizon is short or you are depositing specifically to withdraw, decline the reload at the cashier rather than clicking past it. Withdrawing with an active bonus pending typically voids the bonus and is recorded against your account history.',
      },
    ],
    casinoFilter: () => true,
  },

  cashback: {
    intro:
      'Cashback is the most player-friendly bonus structure in the crypto casino ecosystem because it eliminates the two mechanics that gut the value of every other offer: wagering requirements and maximum cashout caps. The mechanic is direct — the operator returns a percentage of your net losses over a defined period, typically with no playthrough on the returned funds. Percentages range from 5% on entry-level loyalty tiers to 25% at the top VIP grades on platforms like Cloudbet and BC.Game. The critical distinction in the small print is net loss versus gross deposit: legitimate cashback is calculated on (deposits minus withdrawals minus current balance), so a player who deposits $1,000, wins back $400, and finishes the period with $300 in their account has lost $300, not $1,000. Operators that quietly calculate cashback on gross deposits inflate the headline percentage but deliver a fraction of the apparent value. Cashback schedules fall into two buckets: weekly cashback (run by Mirax, Shuffle and BC.Game’s lower VIP tiers) and monthly cashback (favoured by Cloudbet and BitStarz at higher tiers). Weekly is preferable for active players because returns compound earlier into the next play cycle. The reason cashback exists at all is competitive pressure — once a few operators offered no-strings rebates, the rest had to follow or lose VIP volume. From a pure expected-value standpoint, a 10% no-wagering cashback delivers more actual cash than a 200% match bonus at 40x wagering for the majority of player profiles.',
    faqs: [
      {
        q: 'Is cashback calculated on my deposits or my losses?',
        a: 'Legitimate cashback is calculated on net losses, defined as (total deposits in the period minus total withdrawals minus current balance at the end of the period). A 10% weekly cashback on $1,000 deposited and $700 withdrawn with $0 left in the account returns $30 cashback. Operators that calculate on gross deposits inflate the headline number but deliver less. Always check the precise calculation in the terms before relying on the percentage.',
      },
      {
        q: 'Does cashback have wagering requirements?',
        a: 'At reputable crypto casinos, cashback is paid as no-wagering cash you can withdraw immediately — this is the entire appeal of the structure compared with match bonuses. A small number of operators apply a 1x or 5x wagering to cashback, which is still vastly friendlier than the 35x-50x on welcome offers. Cashback with wagering above 10x is unusual and a warning sign about overall bonus practice at that operator.',
      },
      {
        q: 'When does cashback pay out?',
        a: 'Weekly cashback typically credits every Monday for the prior Sun-Sat period. Monthly cashback credits on the 1st of each month for the prior calendar month. Some VIP-tier cashback is paid in real-time as you play, debited against an internal balance that you can withdraw at any point. The timing matters for active players — weekly payouts compound back into bankroll faster than monthly, materially increasing effective return for high-volume play.',
      },
      {
        q: 'Is cashback offered to all players or only VIPs?',
        a: 'Both, depending on operator. BitStarz and Cloudbet reserve their highest cashback tiers (15%-25%) for VIP players but offer entry-tier cashback (5%-10%) to all active accounts. BC.Game, Mirax and Shuffle build cashback into their broader rakeback model and pay it at all levels with tier-based scaling. Entry-tier cashback at most operators activates after a minimum monthly wagering threshold, usually $1,000-$5,000 in turnover.',
      },
      {
        q: 'Can I combine cashback with a welcome or reload bonus?',
        a: 'Yes — cashback is calculated on net losses regardless of how those losses occurred. Losing $500 on a deposit funded by a reload bonus still produces a $500 net loss, which is eligible for cashback. The interaction is one of the few cases where bonus stacking genuinely benefits the player, because it lets you take advantage of multiple structures simultaneously without violating any single offer’s terms. Verify with live chat if you are unsure.',
      },
    ],
    casinoFilter: (c) => c.vipProgram,
  },

  'free-spins': {
    intro:
      'Free spins are the marketing currency of the slots industry, but the gap between headline count and actual value is wider than any other bonus type. A "200 free spins" offer at one operator and a "200 free spins" offer at another can deliver wildly different dollar value depending on three variables buried in the terms: spin value, eligible games and maximum cashout. Spin values typically run $0.10 to $0.20 per spin — meaning a 200-spin pack at $0.10 has a notional value of $20, not the larger sum the marketing implies. Eligible games are usually restricted to a single title or a small curated pool of slots chosen for high volatility and operator-favourable RTP profiles. Common choices include Starburst, Book of Dead and Wolf Gold — established titles that operators have volume-tested and know behave predictably for bonus wagering economics. Maximum cashout caps on free spins winnings sit at $50 to $200 in most cases, even when winnings significantly exceed that figure. Wagering requirements apply to winnings, not the spins themselves, and typically run 35x to 45x of the converted balance. Expiration windows are aggressive — 24 hours is common at smaller operators, 7 days at the larger crypto-native brands. Free spins offered as part of a welcome package (BitStarz: 200 spins; Mirax: 250 spins; 7Bit: 100 spins) carry better terms than standalone promotional spins, because the operator’s economics rely on the matched deposit rather than the spins themselves.',
    faqs: [
      {
        q: 'What is the difference between bonus spins and free spins?',
        a: 'The terms are usually used interchangeably, but at some operators "free spins" credit immediately on deposit with their own terms while "bonus spins" are part of a structured welcome package and inherit the package’s wagering. Free spin packs offered without a deposit carry the harshest terms. Welcome-package spins (BitStarz’s 200, Mirax’s 250, 7Bit’s 100) are generally the most player-friendly tier of spins promotion currently in the market.',
      },
      {
        q: 'What value are free spins played at?',
        a: 'Spin values are typically fixed by the operator, not by the player. The most common values are $0.10 to $0.20 per spin — meaning a 100-spin pack is worth $10-$20 notionally. Some operators credit spins at a higher value ($0.50) for VIP tiers or specific promotions. The spin value determines both the cost to the casino and the realistic profit potential — a $0.10 spin can hit a max win in the thousands, but the cap on cashout usually limits the practical ceiling.',
      },
      {
        q: 'Can I choose which slot to use my free spins on?',
        a: 'Almost never. Free spins are restricted to a specific title or a small handful of titles chosen by the operator — Starburst, Book of Dead, Gates of Olympus and Wolf Gold are the most common picks because they have high volume, well-understood RTP profiles and broad player appeal. The restriction is also commercial: providers pay operators promotional rates to feature their titles in spin campaigns, so the choice of game is partly a marketing arrangement.',
      },
      {
        q: 'What happens if my free spins win exceeds the cashout cap?',
        a: 'Anything above the cap is forfeited. A $50 cashout cap on a free spin promotion means that even if your winnings run to $5,000, the maximum you can withdraw is $50 — the remainder is removed from your balance after the wagering requirement is cleared. Cashout caps are the single most punitive mechanic in free spin promotions, and the reason most experienced players prefer match bonuses with bigger caps over headline spin counts.',
      },
      {
        q: 'Do free spins winnings have wagering requirements?',
        a: 'Yes. The spins themselves are free, but any winnings credit as bonus funds subject to wagering — typically 35x to 45x of the winnings amount. A $25 win from a free spin pack at 40x wagering requires $1,000 of qualifying turnover before the funds become withdrawable. The wagering on free spin winnings is one reason the actual cash extracted from a spin promotion is usually well below what the marketing implies.',
      },
    ],
    casinoFilter: (c) => c.bonusSummary.toLowerCase().includes('spin'),
  },

  'vip-bonus': {
    intro:
      'VIP bonus structures are where crypto casinos do their genuine retention work — the headline welcome offer brings players in, but the VIP programme determines whether they stay. Modern crypto casino VIP systems run on a points-based progression model: every dollar wagered earns loyalty points (typical conversion rates run 1 point per $10 wagered on slots, 1 per $20-$50 on table games), points unlock tier progression, and each tier delivers exclusive bonuses, higher rakeback and dedicated support. Rakeback percentages — the share of house edge returned to the player — range from 5% at entry tier to 20%-25% at the highest grades on BC.Game and Shuffle, both of which built their identity around aggressive VIP returns. Dedicated account managers become available from mid-tier upwards at established platforms (BitStarz, Cloudbet, Mirax), offering bespoke bonus negotiations, faster withdrawal queues and customised reload terms. Exclusive bonuses at top VIP tiers commonly include no-wagering cash drops, birthday bonuses worth several thousand dollars, monthly cashback at the 15%-25% range, and access to high-stakes tournaments closed to general players. The economic logic is durable: a top VIP at a mid-sized crypto casino generates more revenue annually than several hundred casual players combined, and the bonus structures reflect that asymmetry. Point conversion rates and tier requirements are not always published transparently — Shuffle and BC.Game publish full tables, while several others publish only the names of the tiers and reveal the precise progression mechanics only inside the account dashboard once you have qualified.',
    faqs: [
      {
        q: 'How do I qualify for a VIP tier?',
        a: 'Most crypto casinos run automatic tier-based VIP progression based on accumulated wagering. Entry tier typically activates at $1,000-$5,000 total wagering, mid-tier at $50,000-$100,000, and top tier at $1M+ on platforms like BC.Game and Shuffle. Some operators offer invitational top tiers reserved for high-volume players. A faster track to tier exists at some operators through dedicated deposits or by negotiating directly with VIP hosts once you have shown sustained activity.',
      },
      {
        q: 'What is rakeback and how is it calculated?',
        a: 'Rakeback is the percentage of house edge (the casino’s gross win) returned to a player as cash or bonus credit. At crypto casinos it typically runs 5% at entry tiers and scales up to 25% at top VIP. The calculation differs by game type — slots rakeback is based on (turnover times house edge times rakeback rate), so a player wagering $10,000 on a 4% house edge slot at 20% rakeback receives $80 back. Sportsbook rakeback is calculated similarly on net gross gaming revenue.',
      },
      {
        q: 'Are VIP bonuses subject to wagering requirements?',
        a: 'At top tiers, no — the highest-grade VIP cashback, rakeback and exclusive bonuses at established crypto casinos pay as withdrawable cash with no playthrough. At entry and mid tiers, modest wagering (1x-5x) sometimes applies. The shift from wagered to no-wagering bonuses at top VIP is a deliberate retention mechanism — high-volume players have meaningful alternatives and operators compete on terms, not just headline value.',
      },
      {
        q: 'Can I lose my VIP status?',
        a: 'Yes. Most platforms run rolling 30-day or 90-day activity windows: if you do not maintain a minimum wagering volume during the window, your tier drops. The exact thresholds and grace periods vary widely. Top-tier status is usually grandfathered for longer periods (6-12 months) at established operators with dedicated VIP hosts who will reach out before downgrading, but at automated systems the demotion is silent and immediate when the window closes.',
      },
      {
        q: 'Is the VIP programme worth chasing if I am a casual player?',
        a: 'Probably not. The break-even point on VIP value typically sits around $20,000-$50,000 in annual wagering — below that, the bonus value is real but small compared with the volume required. Casual players are better served treating welcome and reload bonuses as the meaningful return and ignoring VIP entirely. For mid-volume players ($100K+ annual wagering), VIP cashback and rakeback can return $1,000-$5,000 a year, which is material.',
      },
    ],
    casinoFilter: (c) => c.vipProgram,
  },

  'high-roller-bonus': {
    intro:
      'High roller bonuses target a structurally different player profile from the standard welcome offer — the minimum qualifying deposit is usually $500 to $5,000, the absolute bonus value scales up to $10,000 or 5 BTC, and the wagering structure is often friendlier than retail bonuses despite the headline numbers being larger. Cloudbet is the most established platform in this segment, with no withdrawal limits and a high-roller welcome package up to 5 BTC. BitStarz operates a similar high-stakes track, and both operators offer named VIP hosts available for personalised bonus negotiation rather than a fixed-terms takeaway. The wagering multiplier on high roller bonuses typically runs 25x to 35x on bonus, against 40x to 50x for standard welcome offers, because operator economics work differently above the $1,000 deposit threshold: marketing cost-per-acquisition matters less when the average customer value is an order of magnitude higher. Withdrawal terms also shift — high rollers usually access expedited payout queues, with crypto withdrawals processed in minutes rather than waiting in the standard verification pipeline. Bet limits on table games run up to $10,000-$100,000 per hand at Evolution VIP tables, available only to verified high rollers. Caveats apply: high roller bonuses commonly require a single-deposit minimum rather than allowing accumulation across multiple smaller transactions, and KYC is mandatory at this tier — the regulatory exposure of paying out six-figure sums to unverified accounts forces full verification even at no-KYC crypto operators. Negotiated terms are common above the $5,000 single-deposit threshold.',
    faqs: [
      {
        q: 'What deposit amount qualifies as "high roller"?',
        a: 'Definitions vary by operator. Cloudbet’s high roller welcome package activates from approximately $1,000 deposit equivalents and scales to 5 BTC. BitStarz treats $500+ as high roller eligible for negotiated terms. Smaller operators may consider $2,000-$5,000 the high roller threshold. The number matters less than the relationship — high roller treatment generally requires a personal conversation with a VIP host rather than self-service through the cashier.',
      },
      {
        q: 'Are high roller bonuses negotiable?',
        a: 'Often yes. Above the $5,000 deposit threshold, most established operators will negotiate custom terms — better wagering ratios, higher cashout caps, personalised reload schedules or no-wagering cashback rates above the standard VIP grid. The negotiation happens through a dedicated VIP host rather than through standard support. Operators willing to negotiate have done so consistently because high roller LTV makes the additional concession economically rational.',
      },
      {
        q: 'Do high roller bonuses have lower wagering requirements?',
        a: 'Typically yes. Standard welcome bonuses carry 40x-50x wagering on bonus or bonus-plus-deposit. High roller bonuses commonly drop to 25x-35x because the absolute bonus value is larger and the operator’s economics scale differently. Some negotiated high roller packages drop wagering further, to 15x-20x. The reduction reflects the underlying mathematics — a 25x wagering on a $50,000 bonus is harder to walk away from than 50x on a $100 retail offer.',
      },
      {
        q: 'Will I have to complete full KYC for high roller bonuses?',
        a: 'Yes, virtually always. Regulatory exposure on payouts above $10,000-$50,000 forces full verification even at otherwise no-KYC operators. Expect to provide government ID, proof of address, source-of-funds documentation for the deposit, and sometimes a video call with the VIP team. The process is usually expedited for high rollers — completion within hours rather than days — but the documents required are more extensive than retail KYC.',
      },
      {
        q: 'Are high roller bonus winnings paid out faster?',
        a: 'Yes. Most established operators run an expedited withdrawal queue for VIP and high roller accounts, with crypto withdrawals processed in minutes rather than the standard 0-24 hour pipeline. Daily and weekly withdrawal limits are also raised significantly — Cloudbet specifically operates with no withdrawal limits for verified high roller accounts. Bank-related friction is reduced by the verified KYC status that high rollers complete in advance of large wins.',
      },
    ],
    casinoFilter: (c) => c.trustScore >= 8.7,
  },
}

export function getCasinosForBonus(slug: string): Casino[] {
  const filter = BONUS_CONTENT[slug]?.casinoFilter ?? (() => true)
  return casinos.filter(filter)
}
